site_name: QGIS GEO Doc
#  favicon : 
#  language: ge
#  icon:
#   logo:
theme:
  name: material
  features:
    - navigation.footer
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.prune
    - navigation.indexes
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - toc.integrate
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - search.highlight
    - search.share
    - search.suggest

#    - header.autohide
#    - announce.dismiss

copyright: Copyright &copy; 2017 - 2024 GIS GEORGIA

extra:
  social:
    - icon: fontawesome/brands/mastodon 
      link: https://fosstodon.org/@squidfunk
      name: squidfunk on Fosstodon
    - icon: fontawesome/brands/facebook
  

  palette: 

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode


  